module.exports = {
propertyImg: [
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House1.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House2.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House3.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House4.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House5.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House6.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House7.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House8.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House9.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House10.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House11.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House12.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House13.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House14.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House15.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House16.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House17.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House18.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House19.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House20.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House21.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House22.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House23.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House24.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House25.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House26.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House27.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House28.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House29.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House30.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House31.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House32.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House33.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House34.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House35.webp",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House36.jpg",
    "https://hackreactor5erfliesmoreplaces.s3-us-west-1.amazonaws.com/airbnb+property+photo/Airbnb+House37.webp",

  ],

  propertyDescription: [
    "Beautiful room overlooking city",
    "Great place for family vacation",
    "Little summer get away home",
    "Private place to relax",
    "Historic house in center of city",
    "Great location in middle of attractions",
    "Lovely place for relaxation",
    "Luxury hide-away",
    "Hakuna Matata - close to downtown",
    "Professionally designed place!",
    "Nantucket Style Beach House",
    "Very large backyard with grill and swings!",
    "House w/big yard!",
    "Pet friendly bungalow",
    "Entire Guesthouse fits plenty",
    "Lots of food and drinks in fridge",
    "How many of these will i write?",
    "Country Cabin in the city",
    "Great location with great views",
    "Don't stay here!",
    "Kanto Region",
    "Hot Spring Onsen",
    "Best place to stay at in the world!",
    "Need to sleep? Heres the place"
  ],

  propertyType: [
    "Entire Place",
    "Private Room",
    "Hotel Room",
    "Shared Room"
  ],
}